# Copyright(c) 2021 aasaam software development group
version: "3"

services:
  sms-gateway-api:
    container_name: sms-gateway-api
    depends_on:
      - sms-gateway-mariadb
    image: aasaam/sms-gateway
    environment:
      ASM_PUBLIC_APP_TEST: "false"
      ASM_MARIADB_DATABASE: ${ASM_MARIADB_DATABASE:-mariadb-db}
      ASM_MARIADB_USER: ${ASM_MARIADB_USER:-mariadb-user}
      ASM_MARIADB_PASSWORD: ${ASM_MARIADB_PASSWORD:-mariadb-password}
      ASM_MARIADB_HOST: ${ASM_MARIADB_HOST:-sms-gateway-mariadb}

  sms-gateway-nginx:
    container_name: sms-gateway-nginx
    image: nginx:1
    depends_on:
      - sms-gateway-api
    ports:
      - 80:80
      # - 443:443
    environment:
      ASM_NGINX_WORKER_PROCESSES: ${ASM_NGINX_WORKER_PROCESSES:-2}
      ASM_NGINX_WORKER_RLIMIT_NOFILE: ${ASM_NGINX_WORKER_RLIMIT_NOFILE:-1024}
      ASM_NGINX_WORKER_CONNECTIONS: ${ASM_NGINX_WORKER_CONNECTIONS:-512}
      ASM_NGINX_ERROR_LOG_LEVEL: ${ASM_NGINX_ERROR_LOG_LEVEL:-warn}
      ASM_APP_PORT: ${ASM_APP_PORT:-3001}
      ASM_PUBLIC_BASE_URL: ${ASM_PUBLIC_BASE_URL:-/}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/common-server.conf:/etc/nginx/common-server.conf:ro
      - ./nginx/common-proxy.conf:/etc/nginx/common-proxy.conf:ro
      - ./nginx/common-http.conf:/etc/nginx/common-http.conf:ro
      - ./nginx/common-protected.conf:/etc/nginx/common-protected.conf:ro
      - ./nginx/templates/default.prod.conf.template:/etc/nginx/templates/default.conf.template:ro
      # - nginx/common-server.conf # For change behind another reverse proxy server

  ################
  # Dependencies #
  ################
  sms-gateway-mariadb:
    container_name: sms-gateway-mariadb
    environment:
      MYSQL_DATABASE: ${ASM_MARIADB_DATABASE:-mariadb-db}
      MYSQL_USER: ${ASM_MARIADB_USER:-mariadb-user}
      MYSQL_PASSWORD: ${ASM_MARIADB_PASSWORD:-mariadb-password}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - sms-gateway-mariadb:/var/lib/mysql
    image: mariadb:10

volumes:
  sms-gateway-mariadb:
